name: Ping Supabase

on:
  schedule:
    - cron: '0 12 * * *'  # каждый день
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl https://onanbtezkaqbhplqlfdp.supabase.co/rest/v1/